config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'

  resources :contacts #, only: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    if @contact = Contact.create(contact_params)
      flash[:success] = "Contact created successfully!"
      redirect_to contacts_path
    end
  end


  private

  def contact_params
    params.require(:contact).permit(:name, :email, :address, :phone_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<header>
  <h1>Contacts</h1>
</header>
<%= link_to 'Add Contact', new_contact_path %>


<% if @contacts.any? %>
  <table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Phone Number</th>
    </tr>

    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.address %></td>
        <td><%= contact.phone_number %></td>
      </tr>
    <% end %>
</table>
<% end %>

app/views/contacts/new.html.erb
<%= form_for @contact do |f| %>

<div class="">
  <%= f.label :name %>:
  <%= f.text_field :name %>
</div>


<div class="">
  <%= f.label :email %>:
  <%= f.text_field :email %>
</div>

<div class="">
  <%= f.label :phone_number %>:
  <%= f.text_field :phone_number %>
</div>

<div class="">
  <%= f.label :address %>:
  <%= f.text_field :address %>
</div>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </body>
</html>